rekit add feature model
rekit add component model/Layout
rekit add component model/ModelsList
rekit add component model/Model
rekit add component model/ViewModel
rekit add feature make
rekit add component make/Layout
rekit add component make/MakesList
rekit add component make/Make
rekit add component make/NewMake
rekit add component make/ViewMake
